---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build-drone-ui
  pull: always
  image: node:14-alpine3.14
  commands:
  # For fuck sake this shit requires python2
  - apk --no-cache add git python2 make g++
  - git clone https://github.com/drone/drone-ui.git -b drone2
  - cd drone-ui
  # Unset CI here because the build fails on warnings when CI=true 🤦
  - unset CI
  # 🤮🤮🤮
  - npm install
  - npm run build

- name: patch
  image: alpine
  pull: always
  commands:
  - apk --no-cache add git
  - git clone https://github.com/drone/drone.git
  - cd drone
  - git config user.name ${DRONE_COMMIT_AUTHOR:-drone}
  - git config user.email ${DRONE_COMMIT_AUTHOR_EMAIL:-builder@drone.spritsail.io}
  - git am ../patches/*

- name: build-drone
  pull: always
  image: golang:alpine
  commands:
  - apk --no-cache add gcc libc-dev
  - go install github.com/bradrydzewski/togo@latest
  - cd drone-ui
  # I have no idea why Go requires this when replacing the module
  - go mod init github.com/drone/drone-ui
  - go generate ./dist
  - cd ../drone
  - go mod edit -replace github.com/drone/drone-ui=../drone-ui
  - go build -a -ldflags "-w -s -extldflags \"-static\"" -o ../release/linux/amd64/drone-server ./cmd/drone-server

- name: build-docker
  pull: always
  image: spritsail/docker-build
  settings:
    dockerfile: drone/docker/Dockerfile.server.linux.amd64

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/drone
    login: {from_secret: docker_login}
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: ca0f6abc799f220e2bc485e16202fce2518a130fedea6775b9e2bb5e9fd527aa

...
