---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

environment:
  DRONE_VERSION: v2.26.0

steps:
- name: build-drone
  pull: always
  image: golang:alpine
  commands:
  - apk --no-cache add gcc libc-dev
  - go build -a -ldflags "-w -s -extldflags \"-static\"" -o release/${DRONE_STAGE_OS}/${DRONE_STAGE_ARCH}/drone-server ./cmd/drone-server

- name: build-docker
  pull: always
  image: spritsail/docker-build
  settings:
    dockerfile: docker/Dockerfile.server.${DRONE_STAGE_OS}.${DRONE_STAGE_ARCH}
    repo: drone/spritsail/drone/${DRONE_BUILD_NUMBER}:${DRONE_STAGE_ARCH}

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: drone/spritsail/drone/${DRONE_BUILD_NUMBER}:${DRONE_STAGE_ARCH}
    repo: spritsail/drone
    login: {from_secret: docker_login}
    tags:
      - latest
      - ${DRONE_VERSION}
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: f03796b92697da3f913cf8d449423494fafcda25839f3372d8d764c7e87207fb

...
